---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: evo-burgers-nfs-pv
  labels:
    app: evo-burgers
spec:
  capacity:
    storage: 100Gi  # advisory only for NFS
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.3.10.253
    path: /bai
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evo-burgers-nfs-pvc
  labels:
    app: evo-burgers
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: evo-burgers-nfs-pv
  storageClassName: ""  # empty to prevent dynamic provisioning

