apiVersion: batch/v1
kind: Job
metadata:
  name: evo-burgers-job
spec:
  template:
    spec:
      containers:
        - name: evo-burgers
          resources:
            limits:
              nvidia.com/gpu: "3" 