apiVersion: batch/v1
kind: Job
metadata:
  name: evo-burgers-job
spec:
  template:
    spec:
      containers:
        - name: evo-burgers
          image: registry.ml-cluster.dei.uc.pt/library/evo-burgers:1.0