apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml

configMapGenerator:
  - name: evo-burgers-config
    files:
      - config.yml

patches:
  - path: gpu-patch.yaml
  - path: image-patch.yaml 